# In terminal to run this file
# docker-compose run app sh -c "django-admin.py startproject app ."
# after "run" is the name of the service
# after "app" is what gets run on the linus container that we created using our docker file
version: "3"

services:
  app:
    build:
      context: .
    ports: #map host to image
      - "8000:8000"
    volumes: # allows us to get the updates to our project into our docker image in real time
      - ./app:/app
    command: > # run application in docker container
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on: # so db container will run before app
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
